export interface GalleryImage {
  src: string;
  alt: string;
  title: string;
  vehicle: string;
  service: "exterior-detail" | "interior-detail" | "exterior-wash";
  serviceLabel: string;
  location: string;
  locationLabel: string;
  width: number;
  height: number;
}

export const galleryImages: GalleryImage[] = [
  {
    src: "/images/toyota-4runner-exterior-detail-honolulu.jpeg",
    alt: "Black Toyota 4Runner TRD exterior detail in residential driveway — Honolulu, Oahu Hawaii",
    title: "Toyota 4Runner TRD — Exterior Detail",
    vehicle: "Toyota 4Runner",
    service: "exterior-detail",
    serviceLabel: "Exterior Detail",
    location: "honolulu",
    locationLabel: "Honolulu",
    width: 1200,
    height: 1600,
  },
  {
    src: "/images/toyota-supra-exterior-detail-honolulu.jpeg",
    alt: "White Toyota GR Supra exterior detail — Honolulu condo parking garage, Oahu Hawaii",
    title: "Toyota GR Supra — Exterior Detail",
    vehicle: "Toyota GR Supra",
    service: "exterior-detail",
    serviceLabel: "Exterior Detail",
    location: "honolulu",
    locationLabel: "Honolulu",
    width: 1600,
    height: 1200,
  },
  {
    src: "/images/bmw-coupe-exterior-detail-mililani.jpeg",
    alt: "Red BMW coupe exterior detail in residential driveway — Mililani, Oahu Hawaii",
    title: "BMW Coupe — Exterior Detail",
    vehicle: "BMW Coupe",
    service: "exterior-detail",
    serviceLabel: "Exterior Detail",
    location: "mililani",
    locationLabel: "Mililani",
    width: 1200,
    height: 1600,
  },
  {
    src: "/images/mercedes-suv-exterior-wash-kailua.jpeg",
    alt: "Black Mercedes-Benz GLE SUV exterior detail in tropical driveway — Kailua, Oahu Hawaii",
    title: "Mercedes-Benz GLE — Exterior Detail",
    vehicle: "Mercedes-Benz GLE",
    service: "exterior-detail",
    serviceLabel: "Exterior Detail",
    location: "kailua",
    locationLabel: "Kailua",
    width: 1200,
    height: 1600,
  },
  {
    src: "/images/bmw-exterior-detail-kapolei.jpeg",
    alt: "Black BMW exterior detail in tropical residential driveway — Kapolei, Oahu Hawaii",
    title: "BMW — Exterior Detail",
    vehicle: "BMW",
    service: "exterior-detail",
    serviceLabel: "Exterior Detail",
    location: "kapolei",
    locationLabel: "Kapolei",
    width: 1200,
    height: 1600,
  },
  {
    src: "/images/foam-wash-mobile-detailing-ewa-beach.jpeg",
    alt: "Mobile car detailing foam wash in progress — Ewa Beach, Oahu Hawaii",
    title: "Foam Exterior Wash — Mobile Detailing",
    vehicle: "Sedan",
    service: "exterior-wash",
    serviceLabel: "Exterior Wash",
    location: "ewa-beach",
    locationLabel: "Ewa Beach",
    width: 1200,
    height: 1600,
  },
  {
    src: "/images/audi-rs-exterior-detail-aiea.jpeg",
    alt: "Dark Audi RS exterior detail in residential driveway — Aiea, Oahu Hawaii",
    title: "Audi RS — Exterior Detail",
    vehicle: "Audi RS",
    service: "exterior-detail",
    serviceLabel: "Exterior Detail",
    location: "aiea",
    locationLabel: "Aiea",
    width: 1200,
    height: 1600,
  },
  {
    src: "/images/mercedes-exterior-detail-hawaii-kai.jpeg",
    alt: "Black Mercedes-Benz exterior detail with luxury wheel detailing — Hawaii Kai, Oahu Hawaii",
    title: "Mercedes-Benz — Exterior & Rim Detail",
    vehicle: "Mercedes-Benz",
    service: "exterior-detail",
    serviceLabel: "Exterior Detail",
    location: "hawaii-kai",
    locationLabel: "Hawaii Kai",
    width: 1600,
    height: 1200,
  },
  {
    src: "/images/toyota-tundra-exterior-detail-kaneohe.jpeg",
    alt: "White Toyota Tundra full-size truck exterior detail — Kaneohe, Oahu Hawaii",
    title: "Toyota Tundra — Exterior Detail",
    vehicle: "Toyota Tundra",
    service: "exterior-detail",
    serviceLabel: "Exterior Detail",
    location: "kaneohe",
    locationLabel: "Kaneohe",
    width: 1200,
    height: 1600,
  },
  {
    src: "/images/bmw-suv-exterior-detail-manoa.jpeg",
    alt: "Red BMW X-Series SUV exterior detail in residential driveway — Manoa, Oahu Hawaii",
    title: "BMW X-Series — Exterior Detail",
    vehicle: "BMW X-Series",
    service: "exterior-detail",
    serviceLabel: "Exterior Detail",
    location: "manoa",
    locationLabel: "Manoa",
    width: 1200,
    height: 1600,
  },
  {
    src: "/images/jeep-wrangler-interior-detail-haleiwa.jpeg",
    alt: "Black Jeep Wrangler interior detail in garage — Haleiwa, North Shore, Oahu Hawaii",
    title: "Jeep Wrangler — Interior Detail",
    vehicle: "Jeep Wrangler",
    service: "interior-detail",
    serviceLabel: "Interior Detail",
    location: "haleiwa",
    locationLabel: "Haleiwa",
    width: 1600,
    height: 1200,
  },
  {
    src: "/images/chrysler-300-exterior-detail-pearl-city.jpeg",
    alt: "White Chrysler 300 exterior detail in residential driveway — Pearl City, Oahu Hawaii",
    title: "Chrysler 300 — Exterior Detail",
    vehicle: "Chrysler 300",
    service: "exterior-detail",
    serviceLabel: "Exterior Detail",
    location: "pearl-city",
    locationLabel: "Pearl City",
    width: 1200,
    height: 1600,
  },
  {
    src: "/images/honda-interior-detail-waimalu.jpeg",
    alt: "Silver Honda interior detail in home garage — Waimalu, Oahu Hawaii",
    title: "Honda — Interior Detail",
    vehicle: "Honda",
    service: "interior-detail",
    serviceLabel: "Interior Detail",
    location: "waimalu",
    locationLabel: "Waimalu",
    width: 1200,
    height: 1600,
  },
  {
    src: "/images/lifted-truck-exterior-detail-ewa-beach.jpeg",
    alt: "White lifted truck exterior detail in tropical driveway — Ewa Beach, Oahu Hawaii",
    title: "Lifted Truck — Exterior Detail",
    vehicle: "Lifted Truck",
    service: "exterior-detail",
    serviceLabel: "Exterior Detail",
    location: "ewa-beach",
    locationLabel: "Ewa Beach",
    width: 1200,
    height: 1600,
  },
  {
    src: "/images/lexus-exterior-detail-kaimuki.jpeg",
    alt: "Dark blue Lexus sedan exterior detail in tropical neighborhood — Kaimuki, Oahu Hawaii",
    title: "Lexus Sedan — Exterior Detail",
    vehicle: "Lexus Sedan",
    service: "exterior-detail",
    serviceLabel: "Exterior Detail",
    location: "kaimuki",
    locationLabel: "Kaimuki",
    width: 1200,
    height: 1600,
  },
  {
    src: "/images/tesla-model3-exterior-detail-honolulu.jpeg",
    alt: "Dark Tesla Model 3 exterior detail — Honolulu condo parking garage, Oahu Hawaii",
    title: "Tesla Model 3 — Exterior Detail",
    vehicle: "Tesla Model 3",
    service: "exterior-detail",
    serviceLabel: "Exterior Detail",
    location: "honolulu",
    locationLabel: "Honolulu",
    width: 1600,
    height: 1200,
  },
  {
    src: "/images/lexus-sedan-exterior-detail-honolulu.jpeg",
    alt: "Silver Lexus sedan exterior detail — Honolulu parking structure, Oahu Hawaii",
    title: "Lexus LS — Exterior Detail",
    vehicle: "Lexus LS",
    service: "exterior-detail",
    serviceLabel: "Exterior Detail",
    location: "honolulu",
    locationLabel: "Honolulu",
    width: 1200,
    height: 1600,
  },
  {
    src: "/images/luxury-suv-exterior-detail-honolulu.jpeg",
    alt: "Black luxury SUV exterior detail — Honolulu condo parking garage, Oahu Hawaii",
    title: "Luxury SUV — Exterior Detail",
    vehicle: "Luxury SUV",
    service: "exterior-detail",
    serviceLabel: "Exterior Detail",
    location: "honolulu",
    locationLabel: "Honolulu",
    width: 1200,
    height: 1600,
  },
  {
    src: "/images/exotic-car-exterior-detail-honolulu.jpeg",
    alt: "White exotic sports car exterior detail — Honolulu parking structure, Oahu Hawaii",
    title: "Exotic Sports Car — Exterior Detail",
    vehicle: "Exotic Sports Car",
    service: "exterior-detail",
    serviceLabel: "Exterior Detail",
    location: "honolulu",
    locationLabel: "Honolulu",
    width: 1200,
    height: 1600,
  },
];

export const homepageGalleryImages = galleryImages.slice(0, 6);
